### ISSUE TITLE
Can't build in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [4xmen/Anubias-Desktop#13]
**Describe the bug**
I can't visit https://anubias.app/,when I visit the website,I got "HTTP ERROR 500",so I just make it from source.
During the process of running `npm install`, the information is as follows:
```
$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v20.2.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated vue-context@6.0.0: No longer maintained
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated particles.vue@2.43.1: Version 2.x is the current version, v1 is obsolete now
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated vazir-font@28.0.0: vazir-font no longer supported. Use vazirmatn instead.
npm WARN deprecated tsparticles@1.43.1: tsParticles 2.6.0 is out, please update

> anubias@1.1.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.14.13

added 1770 packages in 54s
```
When I run `npm run build`,I got errors there:
```
$ npm run build

> anubias@1.1.0 build
> vue-cli-service build


⠹  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:503:5
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:358:12
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠏  Building for production...${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:503:5
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:358:12
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/cache-loader/dist/index.js:147:7
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v20.2.0
```
Then I run `npm run dist`,I got these errors:
```
$ npm run dist

> anubias@1.1.0 dist
> electron-builder --linux snap

  • electron-builder  version=22.14.13 os=6.1.31-1-lts
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=13.6.9 appOutDir=dist/linux-unpacked
  ⨯ Application entry file "background.js" in the "${HOME}/.cache/paru/clone/anubias-1.1.0/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "background.js" in the "${HOME}/.cache/paru/clone/anubias-1.1.0/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at LinuxPackager.checkFileInPackage (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/platformPackager.ts:501:7)
    at LinuxPackager.sanityCheckPackage (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/platformPackager.ts:549:5)
    at LinuxPackager.doPack (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/platformPackager.ts:310:5)
    at LinuxPackager.pack (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/builder-util/src/promise.ts:12:14)
```
When I run `npm run electron:build`,I got this:
```
$ npm run electron:build

> anubias@1.1.0 electron:build
> vue-cli-service electron:build

 INFO  Bundling render process:

⠙  Building modern bundle for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:503:5
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:358:12
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
⠧  Building modern bundle for production...${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:503:5
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/webpack/lib/NormalModule.js:358:12
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/cache-loader/dist/index.js:147:7
    at ${HOME}/.cache/paru/clone/anubias-1.1.0/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.2.0
```
But there still generate an app in dist/linux-unpacked.
When I run the generated `anubias`,error happed:
```
$ ./dist/linux-unpacked/anubias 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/zxp-endeavouros/.cache/paru/clone/anubias-1.1.0/dist/linux-unpacked/resources/app.asar/background.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3197)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
```
**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 6.1.31-1-lts
 - Browser:Slimjet[Based on Chromium 111.0.5563.41]
 - Version:anubias 1.1.0

**Comment by A1Gard** [comment]
Thanks for report

We work on website & refactor, So:

If you wanna just install and use version 1 on linux try https://snapcraft.io/anubias

Otherwise I recommend use `yarn` instead  `npm`, can be help you

BTW if you wanna become a contributor, we work on version 2, right now

**Comment by zxp19821005** [comment]
OK,Thank you!
When I used the Clash-for-Windows,I can visit https://anubias.app/ now,and I can download the AppImage file.
